/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NexaFundWeightedV2 } from "./NexaFundWeightedV2";
export * as factories from "./factories";
export { NexaFundWeightedV2__factory } from "./factories/NexaFundWeightedV2__factory";
